apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tomcat
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: devopskr/apm-demo:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: 500Mi
          limits:
            memory: 1000Mi
        ports:
        - containerPort: 8080
          name: frontend-port
        readinessProbe:
          httpGet:
            path: /test/hello		  
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - mountPath: /etc/localtime
          name: time-conf
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Seoul
        name: time-conf
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat
  labels:
    app: tomcat
spec:
  sessionAffinity: ClientIP
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: frontend-port
    protocol: TCP
    name: http
  selector:
    app: tomcat
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tomcat
spec:
  rules:
  - host: dev.test.com
    http:
      paths:
      - path: /
        backend:
          serviceName: tomcat
          servicePort: 8080
